default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 30
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: landingpage_development
  
test:
  <<: *default
  database: landingpage_test


production:
  adapter: postgresql
  encoding: unicode