# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c68a720473de18a4d9789da81dbc373f80e1d938f460d94c513f50392da6479a8b8596a393b95e2592747afe016e6c01ee4064d8fb230670c4e852872226c052

test:
  secret_key_base: 0d03cf2c8be1ead40bddf7125fb6b9220c26d39b87b57d77306ceb93480512a6679d33279072835cdef65b63fe12b3b9cfb04d8cdca9c715e3614efb3333a52a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
